### ISSUE TITLE
Source to Mosaico

### ISSUE THREAD

**Issue by vladox** [tubaman/django-mosaic#3]
Hi @tubaman  
We are updating the version of Mosaico used with your project but we couldn't find the source to Mosaico in your project. 
We are specially interested in the code where the extra toolbar button "Save template to server" is defined. 
Do you have that part of the source available?
Best 
Vlad

**Comment by tubaman** [comment]
Here's a commit where I update the version of mosaico: https://github.com/tubaman/django-mosaico/commit/7a17e383be8414696d2337998bd551b479baa199

Hope that helps
