### ISSUE TITLE
What is Template and Meta JSON data ?

### ISSUE THREAD

**Issue by niamrox** [tubaman/django-mosaic#4]
Hi,
I am using your app but when creating new template its not saving as Template and Meta JSON field required but what is this ? I only can make HTML for newsletter where I will get JSON or any guideline to make Template and Meta JSON data ?

Also There when I am trying to see frontend of my django site its saying 

`
Page not found (404)
Request Method:	GET
Request URL:	http://localhost:9004/
Using the URLconf defined in mailbuilder.urls, Django tried these URL patterns, in this order:

^admin/
^mosaico/
^media\/(?P<path>.*)$
The empty path didn't match any of these.

You're seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a standard 404 page.
`

**Comment by tubaman** [comment]
>I am using your app but when creating new template its not saving as Template and Meta JSON field required but what is this ? I only can make HTML for newsletter where I will get JSON or any guideline to make Template and Meta JSON data ?

I'm not quite sure what you're asking here.  Have you played around with Mosaico before on it's own(without my Django integration)?  Perhaps that will help.

**Comment by tubaman** [comment]
> Page not found (404)
> Request Method: GET
> Request URL: http://localhost:9004/
> Using the URLconf defined in mailbuilder.urls, Django tried these URL patterns, in this order:
> 
> ^admin/
> ^mosaico/
> ^media/(?P.*)$
> The empty path didn't match any of these.
> 
> You're seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a standard 404 page.
> `

This is a common issue with new Django developers.  As mentioned in [the README](https://github.com/tubaman/django-mosaico/blob/master/README.md), you need to go to http://127.0.0.1:8000/admin/mosaico/template/ see any of the mosaico interface.
