### ISSUE TITLE
Problem uploading images

### ISSUE THREAD

**Issue by umanghce** [tubaman/django-mosaic#5]
While uploading images, I am getting the following error:
    file = request.FILES.values()[0]
TypeError: 'generator' object is not subscriptable

**Comment by huseyinduz** [comment]
Is it late :)

 file = list(request.FILES.values())#[0]
        filex=file[0]
        upload = Upload(name=filex.name, image=filex)

**Comment by tubaman** [comment]
This is probably because I developed this on Django 1.10 and since then Django has changed requests.FILES.values from a list to a generator.  The real answer to this is that I need to [update the app](https://github.com/tubaman/django-mosaico/issues/6) to work with more recent version of Django
